import {Decoder,Stream} from '@garmin/fitsdk';import './style.css';
const $=id=>document.getElementById(id);let rows=[],lastSummary='',fitFile=null,accessToken='';
const GOOGLE_CLIENT_ID='183878529997-llr029n4een3hu8b4c7bh40cfe7flu3g.apps.googleusercontent.com';
$('google').onclick=()=>{if(!window.google){$('driveStatus').textContent='Google-login wordt nog geladen…';return}google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:'https://www.googleapis.com/auth/drive.file',callback:r=>{if(r.error){$('driveStatus').textContent='Drive-koppeling mislukt: '+r.error;return}accessToken=r.access_token;$('driveStatus').textContent='Google Drive gekoppeld.'}}).requestAccessToken({prompt:'consent'})};
const num=(v,d=1)=>v==null?'-':Number(v).toFixed(d);const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
function val(o,...names){for(const n of names)if(o?.[n]!=null)return o[n];return null}
function time(v){if(v instanceof Date)return v.getTime()/1000;if(typeof v==='number')return v>1e12?v/1000:v;return new Date(v).getTime()/1000}
function normalize(r){return{t:time(val(r,'timestamp')),hr:val(r,'heartRate','heart_rate'),cadence:val(r,'cadence'),distance:val(r,'distance'),speed:val(r,'enhancedSpeed','enhanced_speed','speed'),power:val(r,'power'),temp:val(r,'temperature')}}
function pwhr(a){const p=mean(a.map(x=>x.power).filter(Number.isFinite)),h=mean(a.map(x=>x.hr).filter(Number.isFinite));return p!=null&&h? p/h:null}
function np(a){const p=a.map(x=>Number.isFinite(x.power)?x.power:0);if(p.length<30)return null;const roll=[];let sum=0;for(let i=0;i<p.length;i++){sum+=p[i];if(i>=30)sum-=p[i-30];if(i>=29)roll.push(sum/30)}return Math.pow(mean(roll.map(x=>Math.pow(x,4))),.25)}
function analyze(a,ftp){a=a.filter(x=>Number.isFinite(x.t)).sort((x,y)=>x.t-y);const start=a[0].t,end=a.at(-1).t;const moving=a.filter(x=>(x.speed??0)>.5);const powers=moving.map(x=>x.power).filter(Number.isFinite);const positive=powers.filter(x=>x>0);const avgP=mean(powers),pedal=mean(positive),zero=powers.length?powers.filter(x=>x===0).length*100/powers.length:null,hr=mean(moving.map(x=>x.hr).filter(Number.isFinite)),n=np(moving),iff=n&&ftp?n/ftp:null,dur=end-start,tss=iff?dur*iff*iff/36:null,dist=Math.max(...a.map(x=>x.distance).filter(Number.isFinite),0)/1000;const warm=moving.filter(x=>x.t>=start+600),mid=warm.length?(warm[0].t+warm.at(-1).t)/2:start,A=pwhr(warm.filter(x=>x.t<=mid)),B=pwhr(warm.filter(x=>x.t>mid)),dec=A&&B?(A-B)/A*100:null;const blocks=[];for(let from=10;start+from*60<end;from+=20){const q=moving.filter(x=>x.t>=start+from*60&&x.t<start+(from+20)*60);if(q.length)blocks.push({from,to:from+20,p:mean(q.map(x=>x.power).filter(Number.isFinite)),h:mean(q.map(x=>x.hr).filter(Number.isFinite)),e:pwhr(q)})}return{start,dur,dist,avgP,pedal,zero,hr,n,iff,tss,dec,blocks}}
function text(s){const date=new Date(s.start*1000).toLocaleDateString('nl-NL');return[`Datum: ${date}`,`Duur: ${Math.floor(s.dur/3600)}u ${Math.floor(s.dur%3600/60)}m`,`Afstand: ${num(s.dist)} km`,`Gem. vermogen incl. 0 W: ${num(s.avgP)} W`,`Trapvermogen: ${num(s.pedal)} W`,`0 W tijdens bewegen: ${num(s.zero)}%`,`Gem. HR: ${num(s.hr)} bpm`,`NP: ${num(s.n)} W | IF: ${num(s.iff,2)} | TSS: ${num(s.tss)}`,`Pw:HR-decoupling na 10 min: ${num(s.dec)}%`,'20-minutenblokken:',...s.blocks.map(b=>`${b.from}-${b.to}: ${num(b.p)} W / ${num(b.h)} bpm / Pw:HR ${num(b.e,3)}`)].join('\n')}
$('file').onchange=async e=>{try{$('status').textContent='FIT verwerken…';fitFile=e.target.files[0];const buf=await fitFile.arrayBuffer(),decoder=new Decoder(Stream.fromArrayBuffer(buf));if(!decoder.isFIT())throw Error('Dit lijkt geen geldig FIT-bestand.');const {messages,errors}=decoder.read();if(errors?.length)console.warn(errors);const rec=messages.recordMesgs||messages.record_mesgs||messages.records||[];if(!rec.length)throw Error('Geen recordgegevens in FIT gevonden.');rows=rec.map(normalize);const s=analyze(rows,Number($('ftp').value)||295);lastSummary=text(s);$('summary').textContent=lastSummary;$('results').hidden=false;$('status').textContent=`${rows.length} meetpunten verwerkt.`}catch(err){$('status').textContent='Fout: '+err.message;$('results').hidden=true}}
$('copy').onclick=async()=>{const p='Analyseer deze fietstraining volgens mijn vaste aanpak. Beoordeel decoupling, wanneer die begint, vergelijk met recente ritten en houd rekening met intensiteit. Besteed ook aandacht aan uitrollen en trapvermogen.\n\n'+lastSummary;await navigator.clipboard.writeText(p);$('status').textContent='Analyse voor ChatGPT gekopieerd.'}
$('share').onclick=async()=>{const t='Analyseer deze fietstraining volgens mijn vaste aanpak.\n\n'+lastSummary;if(navigator.share)await navigator.share({title:'FIT Ride Analyzer',text:t});else await navigator.clipboard.writeText(t)}
$('csv').onclick=()=>{const head='timestamp,heart_rate,cadence,distance_m,speed_mps,power,temp\n',body=rows.map(x=>[x.t,x.hr??'',x.cadence??'',x.distance??'',x.speed??'',x.power??'',x.temp??''].join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([head+body],{type:'text/csv'}));a.download='fit-ride.csv';a.click();URL.revokeObjectURL(a.href)}
