import {Decoder,Stream} from '@garmin/fitsdk';import './style.css';
const $=id=>document.getElementById(id);let rows=[],lastSummary='',fitFile=null,accessToken='',lastAnalysis=null;
function pressFeedback(b,workingText=null){if(!b)return;b.classList.add('is-working');if(workingText){b.dataset.label=b.textContent;b.textContent=workingText}}
function releaseFeedback(b,doneText=null,delay=900){if(!b)return;if(doneText)b.textContent=doneText;setTimeout(()=>{b.classList.remove('is-working');if(b.dataset.label){b.textContent=b.dataset.label;delete b.dataset.label}},delay)}

const GOOGLE_CLIENT_ID='183878529997-llr029n4een3hu8b4c7bh40cfe7flu3g.apps.googleusercontent.com';
const POWER_MAX=3000;
$('google').onclick=()=>{const b=$('google');pressFeedback(b,'Drive koppelen…');if(!window.google){$('driveStatus').textContent='Google-login wordt nog geladen…';releaseFeedback(b);return}google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:'https://www.googleapis.com/auth/drive.file',callback:r=>{if(r.error){$('driveStatus').textContent='Drive-koppeling mislukt: '+r.error;releaseFeedback(b);return}accessToken=r.access_token;$('driveStatus').textContent='Google Drive gekoppeld ✓';releaseFeedback(b,'Gekoppeld ✓')}}).requestAccessToken({prompt:'consent'})};
const num=(v,d=1)=>v==null?'-':Number(v).toFixed(d),mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
function val(o,...names){for(const n of names)if(o?.[n]!=null)return o[n];return null}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null}
function validPower(v){const n=finite(v);return n!=null&&n>=0&&n<=POWER_MAX?n:null}
function time(v){if(v instanceof Date)return v.getTime()/1000;if(typeof v==='number')return v>1e12?v/1000:v;return new Date(v).getTime()/1000}
function normalize(r){return{t:time(val(r,'timestamp')),hr:finite(val(r,'heartRate','heart_rate')),cadence:finite(val(r,'cadence')),distance:finite(val(r,'distance')),speed:finite(val(r,'enhancedSpeed','enhanced_speed','speed')),power:validPower(val(r,'power')),temp:finite(val(r,'temperature')),altitude:finite(val(r,'enhancedAltitude','enhanced_altitude','altitude'))}}
function ftpForDate(t){return new Date(t*1000).getUTCFullYear()>=2026?290:295}
function moving(a){return a.filter(x=>(x.speed??0)>.5)}
function pwhr(a){const p=mean(a.map(x=>x.power).filter(Number.isFinite)),h=mean(a.map(x=>x.hr).filter(Number.isFinite));return p!=null&&h?p/h:null}
function quality(a){const gaps=[];for(let i=1;i<a.length;i++){const dt=a[i].t-a[i-1].t;if(dt>2)gaps.push(dt)}return{records:a.length,gaps:gaps.length,maxGap:gaps.length?Math.max(...gaps):0,irregular:gaps.filter(x=>x>10).length}}
function powerSegments(a){const segs=[];let cur=[];for(let i=0;i<a.length;i++){const x=a[i];if((x.speed??0)<=.5){if(cur.length)segs.push(cur);cur=[];continue}if(cur.length&&x.t-cur.at(-1).t>2){segs.push(cur);cur=[]}cur.push(x)}if(cur.length)segs.push(cur);return segs.map(seg=>{const out=[];for(let i=0;i<seg.length-1;i++){const x=seg[i],y=seg[i+1],dt=Math.round(y.t-x.t);if(dt<1||dt>2)continue;for(let k=0;k<dt;k++)out.push(Number.isFinite(x.power)?x.power:0)}return out}).filter(x=>x.length)}
function npSegments(segs){const fourth=[];for(const p of segs){if(p.length<30)continue;let sum=0;for(let i=0;i<p.length;i++){sum+=p[i];if(i>=30)sum-=p[i-30];if(i>=29)fourth.push((sum/30)**4)}}return fourth.length?Math.pow(mean(fourth),.25):null}
const Z=[.55,.75,.90,1.05,1.20,1.50,Infinity];
function zones(a,ftp){const sec=Array(7).fill(0);for(let i=0;i<a.length-1;i++){if(!Number.isFinite(a[i].power))continue;const dt=Math.min(10,Math.max(0,a[i+1].t-a[i].t));const z=Z.findIndex(x=>a[i].power<=ftp*x);sec[z<0?6:z]+=dt}return sec}
function bestPowerSegments(segs,seconds){let best=null;for(const p of segs){if(p.length<seconds)continue;let sum=p.slice(0,seconds).reduce((a,b)=>a+b,0);best=Math.max(best??0,sum/seconds);for(let i=seconds;i<p.length;i++){sum+=p[i]-p[i-seconds];best=Math.max(best,sum/seconds)}}return best}
function rollingEfforts(a,ftp,seconds,minRatio){const m=moving(a),out=[];let i=0;while(i<m.length){let j=i,sum=0,n=0;while(j<m.length&&m[j].t-m[i].t<seconds){if(Number.isFinite(m[j].power)){sum+=m[j].power;n++}j++}if(n&&j<m.length&&sum/n>=ftp*minRatio)out.push({t:m[i].t,avg:sum/n});i++}return out}
function structuredCount(points,seconds){if(!points.length)return 0;let groups=1,last=points[0].t;for(const p of points.slice(1)){if(p.t-last>seconds*1.5)groups++;last=p.t}return groups}
function longEnduranceBlock(a,ftp){const m=moving(a).filter(x=>Number.isFinite(x.power));if(m.length<1800)return false;const base=mean(m.map(x=>x.power));if(!base)return false;for(let i=0;i<m.length;i++){let j=i,sum=0,n=0;while(j<m.length&&m[j].t-m[i].t<=1800){sum+=m[j].power;n++;j++}if(j<m.length&&m[j-1].t-m[i].t>=1740){const avg=sum/n;if(avg>=ftp*.65&&avg>=base*1.06)return true}}return false}
function classifyEfforts(a,ftp){const sprint=rollingEfforts(a,ftp,15,1.5),vo2=rollingEfforts(a,ftp,120,1.1),threshold=rollingEfforts(a,ftp,600,.95),tempo=rollingEfforts(a,ftp,900,.65);return{sprint:{windows:sprint.length,groups:structuredCount(sprint,15)},vo2:{windows:vo2.length,groups:structuredCount(vo2,120)},threshold:{windows:threshold.length,groups:structuredCount(threshold,600)},tempo:{windows:tempo.length,groups:structuredCount(tempo,900)},longEndurance:longEnduranceBlock(a,ftp)}}
function profile(s){const pct=s.zoneSec.map(x=>s.movingDur?100*x/s.movingDur:0),hard=pct[4]+pct[5]+pct[6],e=s.efforts;if(e.vo2.groups>=4&&e.vo2.windows>=240)return pct[1]>=35?'endurance_with_vo2_intervals':'vo2_intervals';if(e.threshold.groups>=2&&e.threshold.windows>=600)return pct[1]>=35?'endurance_with_threshold_blocks':'threshold_intervals';if(pct[2]>=25)return'tempo';if(pct[1]>=45&&hard<5&&e.longEndurance)return'endurance_with_blocks';if(pct[1]>=45&&hard<5)return'endurance';if(e.sprint.groups>=6&&e.sprint.windows>=60)return'sprint_or_anaerobic';return'mixed'}
function analyze(a,ftpOverride=null){a=a.filter(x=>Number.isFinite(x.t)).sort((x,y)=>x.t-y);const start=a[0].t,end=a.at(-1).t,ftp=ftpOverride||ftpForDate(start),m=moving(a),powers=m.map(x=>x.power).filter(Number.isFinite),positive=powers.filter(x=>x>0),avgP=mean(powers),pedal=mean(positive),zero=powers.length?100*powers.filter(x=>x===0).length/powers.length:null,hrs=m.map(x=>x.hr).filter(Number.isFinite),hr=mean(hrs),maxHr=hrs.length?Math.max(...hrs):null,segs=powerSegments(a),n=npSegments(segs),iff=n/ftp,dur=end-start,movingDur=m.length>1?m.slice(0,-1).reduce((s,x,i)=>s+Math.min(10,Math.max(0,m[i+1].t-x.t)),0):0,tss=iff?movingDur*iff*iff/36:null,dist=Math.max(...a.map(x=>x.distance).filter(Number.isFinite),0)/1000,zoneSec=zones(m,ftp);const warm=m.filter(x=>x.t>=start+600),mid=warm.length?(warm[0].t+warm.at(-1).t)/2:start,A=pwhr(warm.filter(x=>x.t<=mid)),B=pwhr(warm.filter(x=>x.t>mid)),dec=A&&B?(A-B)/A*100:null,blocks=[];for(let from=10;start+from*60<end;from+=20){const q=m.filter(x=>x.t>=start+from*60&&x.t<start+(from+20)*60);if(q.length)blocks.push({from,to:from+20,p:mean(q.map(x=>x.power).filter(Number.isFinite)),h:mean(q.map(x=>x.hr).filter(Number.isFinite)),e:pwhr(q)})}const s={start,dur,movingDur,dist,ftp,avgP,pedal,zero,hr,maxHr,n,iff,tss,dec,zoneSec,quality:quality(a),efforts:classifyEfforts(a,ftp),best:{p5:bestPowerSegments(segs,5),p30:bestPowerSegments(segs,30),p60:bestPowerSegments(segs,60),p300:bestPowerSegments(segs,300),p1200:bestPowerSegments(segs,1200),p3600:bestPowerSegments(segs,3600)},blocks};s.profile=profile(s);return s}
function text(s){const date=new Date(s.start*1000).toLocaleDateString('nl-NL');return[`Datum: ${date}`,`FTP gebruikt: ${s.ftp} W`,`Trainingsprofiel: ${s.profile}`,`Duur: ${Math.floor(s.dur/3600)}u ${Math.floor(s.dur%3600/60)}m | bewegen: ${Math.floor(s.movingDur/3600)}u ${Math.floor(s.movingDur%3600/60)}m`,`Afstand: ${num(s.dist)} km`,`Gem. vermogen incl. 0 W tijdens bewegen: ${num(s.avgP)} W`,`Gem. vermogen excl. 0 W tijdens bewegen (trapvermogen): ${num(s.pedal)} W`,`0 W tijdens bewegen: ${num(s.zero)}%`,`Gem./max HR: ${num(s.hr)} / ${num(s.maxHr)} bpm`,`NP: ${num(s.n)} W | IF: ${num(s.iff,2)} | TSS: ${num(s.tss)}`,`Zones (% beweegtijd): ${s.zoneSec.map((x,i)=>`Z${i+1} ${num(100*x/s.movingDur)}%`).join(' | ')}`,`Beste vermogen: 5s ${num(s.best.p5)} | 30s ${num(s.best.p30)} | 1m ${num(s.best.p60)} | 5m ${num(s.best.p300)} | 20m ${num(s.best.p1200)} | 60m ${num(s.best.p3600)} W`,`Pw:HR-decoupling na 10 min: ${num(s.dec)}%`,...(s.quality.gaps?[`Tijdreeks: ${s.quality.gaps} onderbrekingen >2 s; grootste ${num(s.quality.maxGap,0)} s. Berekeningen houden rekening met onderbrekingen.`]:[]),'20-minutenblokken:',...s.blocks.map(b=>`${b.from}-${b.to}: ${num(b.p)} W / ${num(b.h)} bpm / Pw:HR ${num(b.e,3)}`)].join('\n')}
function csvData(a){const start=a.find(x=>Number.isFinite(x.t))?.t??0,head='timestamp,elapsed_seconds,heart_rate_bpm,cadence_rpm,distance_m,speed_mps,power_w,temperature_c,altitude_m\n',body=a.map(x=>[new Date(x.t*1000).toISOString(),num(x.t-start,0),x.hr??'',x.cadence??'',x.distance??'',x.speed??'',x.power??'',x.temp??'',x.altitude??''].join(',')).join('\n');return head+body}
function fitSport(messages){const sessions=messages.sessionMesgs||messages.session_mesgs||messages.sessions||[],acts=messages.activityMesgs||messages.activity_mesgs||messages.activities||[],files=messages.fileIdMesgs||messages.file_id_mesgs||messages.fileIds||[];const raw=val(sessions[0],'sport','subSport','sub_sport')??val(acts[0],'sport')??val(files[0],'sport');return raw==null?'':String(raw).toLowerCase()}
function isCyclingSport(sport){return sport==='cycling'||sport==='bike'||sport==='biking'||sport.includes('cycl')||sport.includes('bike')}
async function parseFile(file,ftpOverride=null){const buf=await file.arrayBuffer(),decoder=new Decoder(Stream.fromArrayBuffer(buf));if(!decoder.isFIT())throw Error(file.name+': geen geldig FIT-bestand');const {messages}=decoder.read(),rec=messages.recordMesgs||messages.record_mesgs||messages.records||[];if(!rec.length)throw Error(file.name+': geen recordgegevens');const sport=fitSport(messages),r=rec.map(normalize),s=analyze(r,ftpOverride);return{rows:r,summary:s,csv:csvData(r),sport}}
$('file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;$('status').textContent='FIT verwerken…';fitFile=file;if(!accessToken)throw Error('Koppel eerst Google Drive.');const out=await parseFile(fitFile,Number($('ftp').value)||290);rows=out.rows;lastAnalysis=out.summary;lastSummary=text(out.summary);$('summary').textContent=lastSummary;$('status').textContent='Opslaan op Google Drive…';await saveCurrentToDrive();$('status').textContent='Opgeslagen ✓'}catch(err){$('status').textContent='Fout: '+err.message;$('results').hidden=true}}
$('bulk').onchange=async e=>{const files=[...e.target.files].filter(f=>f.name.toLowerCase().endsWith('.fit'));if(!files.length)return;if(!accessToken){$('bulkStatus').textContent='Koppel eerst Google Drive en kies daarna de historische bestanden opnieuw.';return}$('bulk').disabled=true;const counts={seen:0,saved:0,nonBike:0,old:0,existing:0,error:0};const show=()=>{$('bulkStatus').textContent=`${counts.seen} / ${files.length} bekeken — ${counts.saved} fietsritten opgeslagen — ${counts.nonBike} geen fietsrit — ${counts.old} te oud — ${counts.existing} bestaand — ${counts.error} fouten`};show();try{const root=await ensureFolder('FIT Ride Analyzer',null),folderCache={},newRows=[];let reg=await findDriveFile('ritten.csv',root.id),txt=registerHeader()+'\n';if(reg){const rr=await driveFetch('https://www.googleapis.com/drive/v3/files/'+reg.id+'?alt=media');txt=await rr.text();if(!txt.trim())txt=registerHeader()+'\n'}let lines=txt.trimEnd().split('\n');const known=new Set(lines.slice(1).map(x=>x.split(',')[0]).filter(Boolean));for(const f of files){try{const out=await parseFile(f,null);if(!isCyclingSport(out.sport)){counts.nonBike++;continue}const date=new Date(out.summary.start*1000),cutoff=new Date('2024-10-04T00:00:00Z');if(date<cutoff){counts.old++;continue}const base=date.toISOString().replace(/[-:]/g,'').replace(/\.000Z$/,'Z');if(known.has(base)){counts.existing++;continue}const year=date.getUTCFullYear();if(!folderCache[year]){const yf=await ensureFolder(String(year),root.id);folderCache[year]={fit:await ensureFolder('fit',yf.id),csv:await ensureFolder('csv',yf.id)}}const dirs=folderCache[year],fitName=base+'.fit',csvName=base+'.csv';const existingFit=await findDriveFile(fitName,dirs.fit.id),existingCsv=await findDriveFile(csvName,dirs.csv.id);if(existingFit&&existingCsv){counts.existing++;known.add(base);continue}await uploadMultipart(fitName,dirs.fit.id,f,'application/octet-stream',existingFit?.id);await uploadMultipart(csvName,dirs.csv.id,new Blob([out.csv],{type:'text/csv'}),'text/csv',existingCsv?.id);newRows.push({id:base,row:registerRow(out.summary,f.name)});known.add(base);counts.saved++}catch(err){counts.error++}finally{counts.seen++;show()}}for(const r of newRows)lines.push(r.row);if(newRows.length)await uploadMultipart('ritten.csv',root.id,new Blob([lines.join('\n')+'\n'],{type:'text/csv'}),'text/csv',reg?.id);$('bulkStatus').textContent='Klaar ✓ — '+$('bulkStatus').textContent;$('bulk').disabled=false}catch(err){$('bulk').disabled=false;$('bulkStatus').textContent='Bulkimport gestopt: '+err.message}}

async function driveFetch(url,options={}){if(!accessToken)throw Error('Koppel eerst Google Drive.');const r=await fetch(url,{...options,headers:{Authorization:'Bearer '+accessToken,...(options.headers||{})}});if(!r.ok)throw Error('Google Drive: '+r.status+' '+await r.text());return r}
async function findDriveFile(name,parentId,mimeType=null){const q=[`name='${name.replaceAll("'","\\'")}'`,`'${parentId}' in parents`,'trashed=false'];if(mimeType)q.push(`mimeType='${mimeType}'`);const u='https://www.googleapis.com/drive/v3/files?q='+encodeURIComponent(q.join(' and '))+'&fields=files(id,name,mimeType)&spaces=drive';const r=await driveFetch(u);return (await r.json()).files?.[0]||null}
async function createFolder(name,parentId){const r=await driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:parentId?[parentId]:undefined})});return await r.json()}
async function ensureFolder(name,parentId){return await findDriveFile(name,parentId||'root','application/vnd.google-apps.folder')||await createFolder(name,parentId)}
async function uploadMultipart(name,parentId,blob,mimeType,existingId=null){const meta={name,mimeType,parents:existingId?undefined:[parentId]},boundary='fitride_'+Date.now(),head='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: '+mimeType+'\r\n\r\n',tail='\r\n--'+boundary+'--',body=new Blob([head,blob,tail],{type:'multipart/related; boundary='+boundary}),url=existingId?'https://www.googleapis.com/upload/drive/v3/files/'+existingId+'?uploadType=multipart&fields=id,name':'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name';const r=await driveFetch(url,{method:existingId?'PATCH':'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});return await r.json()}
function csvEscape(v){const s=String(v??'');return /[,"\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s}
function registerHeader(){return['ride_id','date','start_time','source_fit','ftp_used','training_profile','duration_s','moving_time_s','distance_km','avg_power_moving_w','avg_pedaling_power_w','zero_power_pct','avg_hr_bpm','max_hr_bpm','np_w','if','tss','z1_pct','z2_pct','z3_pct','z4_pct','z5_pct','z6_pct','z7_pct','best_5s_w','best_30s_w','best_1m_w','best_5m_w','best_20m_w','best_60m_w','decoupling_pct'].join(',')}
function registerRow(s,fileName){const d=new Date(s.start*1000),z=s.zoneSec.map(x=>s.movingDur?100*x/s.movingDur:0),id=d.toISOString().replace(/[-:]/g,'').replace(/\.000Z$/,'Z');return[id,d.toISOString().slice(0,10),d.toISOString().slice(11,19),fileName,s.ftp,s.profile,Math.round(s.dur),Math.round(s.movingDur),s.dist,s.avgP,s.pedal,s.zero,s.hr,s.maxHr,s.n,s.iff,s.tss,...z,s.best.p5,s.best.p30,s.best.p60,s.best.p300,s.best.p1200,s.best.p3600,s.dec].map(csvEscape).join(',')}
async function saveCurrentToDrive(){if(!fitFile||!lastAnalysis)throw Error('Kies eerst een FIT-bestand.');const root=await ensureFolder('FIT Ride Analyzer',null),year=String(new Date(lastAnalysis.start*1000).getUTCFullYear()),yf=await ensureFolder(year,root.id),ff=await ensureFolder('fit',yf.id),cf=await ensureFolder('csv',yf.id),base=new Date(lastAnalysis.start*1000).toISOString().replace(/[-:]/g,'').replace(/\.000Z$/,'Z'),fitName=base+'.fit',csvName=base+'.csv';let ex=await findDriveFile(fitName,ff.id);await uploadMultipart(fitName,ff.id,fitFile,'application/octet-stream',ex?.id);ex=await findDriveFile(csvName,cf.id);await uploadMultipart(csvName,cf.id,new Blob([csvData(rows)],{type:'text/csv'}),'text/csv',ex?.id);let reg=await findDriveFile('ritten.csv',root.id),txt=registerHeader()+'\n';if(reg){const rr=await driveFetch('https://www.googleapis.com/drive/v3/files/'+reg.id+'?alt=media');txt=await rr.text();if(!txt.trim())txt=registerHeader()+'\n'}const rideId=base,lines=txt.trimEnd().split('\n'),row=registerRow(lastAnalysis,fitFile.name),idx=lines.findIndex((x,i)=>i>0&&x.startsWith(rideId+','));if(idx>=0)lines[idx]=row;else lines.push(row);txt=lines.join('\n')+'\n';await uploadMultipart('ritten.csv',root.id,new Blob([txt],{type:'text/csv'}),'text/csv',reg?.id);return{fitName,csvName}}
