import {Decoder,Stream} from '@garmin/fitsdk';import './style.css';
const $=id=>document.getElementById(id);let rows=[],lastSummary='',fitFile=null,accessToken='';
const GOOGLE_CLIENT_ID='183878529997-llr029n4een3hu8b4c7bh40cfe7flu3g.apps.googleusercontent.com';
const POWER_MAX=3000;
$('google').onclick=()=>{if(!window.google){$('driveStatus').textContent='Google-login wordt nog geladen…';return}google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:'https://www.googleapis.com/auth/drive.file',callback:r=>{if(r.error){$('driveStatus').textContent='Drive-koppeling mislukt: '+r.error;return}accessToken=r.access_token;$('driveStatus').textContent='Google Drive gekoppeld.'}}).requestAccessToken({prompt:'consent'})};
const num=(v,d=1)=>v==null?'-':Number(v).toFixed(d),mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
function val(o,...names){for(const n of names)if(o?.[n]!=null)return o[n];return null}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null}
function validPower(v){const n=finite(v);return n!=null&&n>=0&&n<=POWER_MAX?n:null}
function time(v){if(v instanceof Date)return v.getTime()/1000;if(typeof v==='number')return v>1e12?v/1000:v;return new Date(v).getTime()/1000}
function normalize(r){return{t:time(val(r,'timestamp')),hr:finite(val(r,'heartRate','heart_rate')),cadence:finite(val(r,'cadence')),distance:finite(val(r,'distance')),speed:finite(val(r,'enhancedSpeed','enhanced_speed','speed')),power:validPower(val(r,'power')),temp:finite(val(r,'temperature')),altitude:finite(val(r,'enhancedAltitude','enhanced_altitude','altitude'))}}
function ftpForDate(t){return new Date(t*1000).getUTCFullYear()>=2026?290:295}
function moving(a){return a.filter(x=>(x.speed??0)>.5)}
function pwhr(a){const p=mean(a.map(x=>x.power).filter(Number.isFinite)),h=mean(a.map(x=>x.hr).filter(Number.isFinite));return p!=null&&h?p/h:null}
function quality(a){const gaps=[];for(let i=1;i<a.length;i++){const dt=a[i].t-a[i-1].t;if(dt>2)gaps.push(dt)}return{records:a.length,gaps:gaps.length,maxGap:gaps.length?Math.max(...gaps):0,irregular:gaps.filter(x=>x>10).length}}
function powerSegments(a){const segs=[];let cur=[];for(let i=0;i<a.length;i++){const x=a[i];if((x.speed??0)<=.5){if(cur.length)segs.push(cur);cur=[];continue}if(cur.length&&x.t-cur.at(-1).t>2){segs.push(cur);cur=[]}cur.push(x)}if(cur.length)segs.push(cur);return segs.map(seg=>{const out=[];for(let i=0;i<seg.length-1;i++){const x=seg[i],y=seg[i+1],dt=Math.round(y.t-x.t);if(dt<1||dt>2)continue;for(let k=0;k<dt;k++)out.push(Number.isFinite(x.power)?x.power:0)}return out}).filter(x=>x.length)}
function npSegments(segs){const fourth=[];for(const p of segs){if(p.length<30)continue;let sum=0;for(let i=0;i<p.length;i++){sum+=p[i];if(i>=30)sum-=p[i-30];if(i>=29)fourth.push((sum/30)**4)}}return fourth.length?Math.pow(mean(fourth),.25):null}
const Z=[.55,.75,.90,1.05,1.20,1.50,Infinity];
function zones(a,ftp){const sec=Array(7).fill(0);for(let i=0;i<a.length-1;i++){if(!Number.isFinite(a[i].power))continue;const dt=Math.min(10,Math.max(0,a[i+1].t-a[i].t));const z=Z.findIndex(x=>a[i].power<=ftp*x);sec[z<0?6:z]+=dt}return sec}
function bestPowerSegments(segs,seconds){let best=null;for(const p of segs){if(p.length<seconds)continue;let sum=p.slice(0,seconds).reduce((a,b)=>a+b,0);best=Math.max(best??0,sum/seconds);for(let i=seconds;i<p.length;i++){sum+=p[i]-p[i-seconds];best=Math.max(best,sum/seconds)}}return best}
function rollingEfforts(a,ftp,seconds,minRatio){const m=moving(a),out=[];let i=0;while(i<m.length){let j=i,sum=0,n=0;while(j<m.length&&m[j].t-m[i].t<seconds){if(Number.isFinite(m[j].power)){sum+=m[j].power;n++}j++}if(n&&j<m.length&&sum/n>=ftp*minRatio)out.push({t:m[i].t,avg:sum/n});i++}return out}
function structuredCount(points,seconds){if(!points.length)return 0;let groups=1,last=points[0].t;for(const p of points.slice(1)){if(p.t-last>seconds*1.5)groups++;last=p.t}return groups}
function classifyEfforts(a,ftp){const sprint=rollingEfforts(a,ftp,15,1.5),vo2=rollingEfforts(a,ftp,120,1.1),threshold=rollingEfforts(a,ftp,600,.95),tempo=rollingEfforts(a,ftp,900,.65);return{sprint:{windows:sprint.length,groups:structuredCount(sprint,15)},vo2:{windows:vo2.length,groups:structuredCount(vo2,120)},threshold:{windows:threshold.length,groups:structuredCount(threshold,600)},tempo:{windows:tempo.length,groups:structuredCount(tempo,900)}}}
function profile(s){const pct=s.zoneSec.map(x=>s.movingDur?100*x/s.movingDur:0),hard=pct[4]+pct[5]+pct[6],e=s.efforts;if(e.vo2.groups>=4&&e.vo2.windows>=240)return pct[1]>=35?'endurance_with_vo2_intervals':'vo2_intervals';if(e.threshold.groups>=2&&e.threshold.windows>=600)return pct[1]>=35?'endurance_with_threshold_blocks':'threshold_intervals';if(pct[2]>=25)return'tempo';if(pct[1]>=45&&hard<5&&e.tempo.windows>=1200)return'endurance_with_blocks';if(pct[1]>=45&&hard<5)return'endurance';if(e.sprint.groups>=6&&e.sprint.windows>=60)return'sprint_or_anaerobic';return'mixed'}
function analyze(a,ftpOverride=null){a=a.filter(x=>Number.isFinite(x.t)).sort((x,y)=>x.t-y);const start=a[0].t,end=a.at(-1).t,ftp=ftpOverride||ftpForDate(start),m=moving(a),powers=m.map(x=>x.power).filter(Number.isFinite),positive=powers.filter(x=>x>0),avgP=mean(powers),pedal=mean(positive),zero=powers.length?100*powers.filter(x=>x===0).length/powers.length:null,hrs=m.map(x=>x.hr).filter(Number.isFinite),hr=mean(hrs),maxHr=hrs.length?Math.max(...hrs):null,segs=powerSegments(a),n=npSegments(segs),iff=n/ftp,dur=end-start,movingDur=m.length>1?m.slice(0,-1).reduce((s,x,i)=>s+Math.min(10,Math.max(0,m[i+1].t-x.t)),0):0,tss=iff?movingDur*iff*iff/36:null,dist=Math.max(...a.map(x=>x.distance).filter(Number.isFinite),0)/1000,zoneSec=zones(m,ftp);const warm=m.filter(x=>x.t>=start+600),mid=warm.length?(warm[0].t+warm.at(-1).t)/2:start,A=pwhr(warm.filter(x=>x.t<=mid)),B=pwhr(warm.filter(x=>x.t>mid)),dec=A&&B?(A-B)/A*100:null,blocks=[];for(let from=10;start+from*60<end;from+=20){const q=m.filter(x=>x.t>=start+from*60&&x.t<start+(from+20)*60);if(q.length)blocks.push({from,to:from+20,p:mean(q.map(x=>x.power).filter(Number.isFinite)),h:mean(q.map(x=>x.hr).filter(Number.isFinite)),e:pwhr(q)})}const s={start,dur,movingDur,dist,ftp,avgP,pedal,zero,hr,maxHr,n,iff,tss,dec,zoneSec,quality:quality(a),efforts:classifyEfforts(a,ftp),best:{p5:bestPowerSegments(segs,5),p30:bestPowerSegments(segs,30),p60:bestPowerSegments(segs,60),p300:bestPowerSegments(segs,300),p1200:bestPowerSegments(segs,1200),p3600:bestPowerSegments(segs,3600)},blocks};s.profile=profile(s);return s}
function text(s){const date=new Date(s.start*1000).toLocaleDateString('nl-NL');return[`Datum: ${date}`,`FTP gebruikt: ${s.ftp} W`,`Trainingsprofiel: ${s.profile}`,`Duur: ${Math.floor(s.dur/3600)}u ${Math.floor(s.dur%3600/60)}m | bewegen: ${Math.floor(s.movingDur/3600)}u ${Math.floor(s.movingDur%3600/60)}m`,`Afstand: ${num(s.dist)} km`,`Gem. vermogen incl. 0 W tijdens bewegen: ${num(s.avgP)} W`,`Gem. vermogen excl. 0 W tijdens bewegen (trapvermogen): ${num(s.pedal)} W`,`0 W tijdens bewegen: ${num(s.zero)}%`,`Gem./max HR: ${num(s.hr)} / ${num(s.maxHr)} bpm`,`NP: ${num(s.n)} W | IF: ${num(s.iff,2)} | TSS: ${num(s.tss)}`,`Zones (% beweegtijd): ${s.zoneSec.map((x,i)=>`Z${i+1} ${num(100*x/s.movingDur)}%`).join(' | ')}`,`Beste vermogen: 5s ${num(s.best.p5)} | 30s ${num(s.best.p30)} | 1m ${num(s.best.p60)} | 5m ${num(s.best.p300)} | 20m ${num(s.best.p1200)} | 60m ${num(s.best.p3600)} W`,`Pw:HR-decoupling na 10 min: ${num(s.dec)}%`,...(s.quality.gaps?[`Tijdreeks: ${s.quality.gaps} onderbrekingen >2 s; grootste ${num(s.quality.maxGap,0)} s. Berekeningen houden rekening met onderbrekingen.`]:[]),'20-minutenblokken:',...s.blocks.map(b=>`${b.from}-${b.to}: ${num(b.p)} W / ${num(b.h)} bpm / Pw:HR ${num(b.e,3)}`)].join('\n')}
function csvData(a){const start=a.find(x=>Number.isFinite(x.t))?.t??0,head='timestamp,elapsed_seconds,heart_rate_bpm,cadence_rpm,distance_m,speed_mps,power_w,temperature_c,altitude_m\n',body=a.map(x=>[new Date(x.t*1000).toISOString(),num(x.t-start,0),x.hr??'',x.cadence??'',x.distance??'',x.speed??'',x.power??'',x.temp??'',x.altitude??''].join(',')).join('\n');return head+body}
async function parseFile(file,ftpOverride=null){const buf=await file.arrayBuffer(),decoder=new Decoder(Stream.fromArrayBuffer(buf));if(!decoder.isFIT())throw Error(file.name+': geen geldig FIT-bestand');const {messages}=decoder.read(),rec=messages.recordMesgs||messages.record_mesgs||messages.records||[];if(!rec.length)throw Error(file.name+': geen recordgegevens');const r=rec.map(normalize),s=analyze(r,ftpOverride);return{rows:r,summary:s,csv:csvData(r)}}
$('file').onchange=async e=>{try{$('status').textContent='FIT verwerken…';fitFile=e.target.files[0];const out=await parseFile(fitFile,Number($('ftp').value)||290);rows=out.rows;lastSummary=text(out.summary);$('summary').textContent=lastSummary;$('results').hidden=false;$('status').textContent=`${rows.length} meetpunten verwerkt.`}catch(err){$('status').textContent='Fout: '+err.message;$('results').hidden=true}}
$('bulk').onchange=async e=>{const files=[...e.target.files].filter(f=>f.name.toLowerCase().endsWith('.fit'));if(!files.length)return;$('bulkStatus').textContent=`${files.length} historische ritten verwerken…`;let ok=0,skip=0;for(const f of files){try{const out=await parseFile(f,null),year=new Date(out.summary.start*1000).getUTCFullYear();if(year<2024||(year===2024&&new Date(out.summary.start*1000)<new Date('2024-10-04T00:00:00Z'))){skip++;continue}ok++}catch{skip++}}$('bulkStatus').textContent=`Klaar: ${ok} ritten geschikt voor import, ${skip} overgeslagen. Drive-opslag volgt in de volgende stap.`}
$('copy').onclick=async()=>{const p='Analyseer deze fietstraining volgens mijn vaste aanpak. Beoordeel decoupling, wanneer die begint, vergelijk met recente ritten en houd rekening met intensiteit. Besteed ook aandacht aan uitrollen, trapvermogen, automatische trainingsprofilering en intensiteitsverdeling.\n\n'+lastSummary;await navigator.clipboard.writeText(p);$('status').textContent='Analyse voor ChatGPT gekopieerd.'}
$('share').onclick=async()=>{const t='Analyseer deze fietstraining volgens mijn vaste aanpak.\n\n'+lastSummary;if(navigator.share)await navigator.share({title:'FIT Ride Analyzer',text:t});else await navigator.clipboard.writeText(t)}
$('csv').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csvData(rows)],{type:'text/csv'}));a.download=(fitFile?.name||'fit-ride').replace(/\.fit$/i,'')+'.csv';a.click();URL.revokeObjectURL(a.href)}
